Repository BR0kEN-/cikit, pull requests merged in 2018-03, with the labels that each got.

#102 #101: Improve API for integrating new CMF/CMS
  .travis.yml
  cmf/drupal/main.yml
  cmf/wordpress/main.yml
  docs/_changelog/2018-03-04/README.md
  docs/_data/navigation.yml
  docs/_documentation/project/cmf-integration/README.md
  scripts/init.yml
  tests/travis/init.sh
Labels: enhancement

#100 #99: Add virtual hosts aliases to the "hosts" file
  cmf/all/.cikit/vars/web-server.yml
  docs/_changelog/2018-03-06/README.md
  docs/_changelog/2018-03-06/images/cikit-1.0.3-migration-note.png
  docs/_data/navigation.yml
  docs/_documentation/project/custom-vhosts/README.md
  docs/_documentation/project/custom-vhosts/images/cikit-vagrant-up.png
  docs/_documentation/project/custom-vhosts/images/web-server-vhosts.png
  docs/_documentation/project/mssql/README.md
  lib/.version
  scripts/roles/cikit-apache2/tasks/configure.yml
  scripts/roles/cikit-apache2/tasks/create-configs.yml
  scripts/roles/cikit-apache2/templates/common/ports.conf.j2
  scripts/roles/cikit-apache2/templates/common/ssl.conf.j2
  scripts/roles/cikit-apache2/templates/parts/directory.j2
  scripts/roles/cikit-apache2/templates/vhosts.conf.j2
  scripts/roles/cikit-nginx/tasks/main.yml
  scripts/roles/cikit-nginx/tasks/vhost.yml
  scripts/roles/cikit-nginx/templates/cikit.j2
  scripts/roles/cikit-nginx/templates/nginx.conf.j2
  scripts/roles/cikit-nginx/templates/parts/locations.j2
  scripts/roles/cikit-nginx/templates/parts/logs.j2
  scripts/roles/cikit-nginx/templates/parts/proxy-pass.j2
  scripts/roles/cikit-nginx/templates/snippets/proxy-pass.conf.j2
  scripts/roles/cikit-nginx/templates/snippets/site-locations.conf.j2
  scripts/roles/cikit-nginx/templates/snippets/ssl.conf.j2
  scripts/roles/cikit-nginx/templates/vhosts.conf.j2
  scripts/tasks/migrations/1.0.3.yml
  vagrant/Vagrantfile
  vagrant/message.rb
Labels: enhancement

#105 Entry for non-standard PHP extensions.
  scripts/roles/cikit-php/defaults/main.yml
  scripts/roles/cikit-php/tasks/main.yml
Labels: enhancement

#104 #95: Add Platform.sh integration
  cmf/all/.gitignore
  cmf/all/scripts/tasks/database/import-strategies/platformsh.yml
  docs/_changelog/2018-03-10/README.md
  docs/_data/navigation.yml
  docs/_documentation/project/mysql-import-strategies/README.md
  docs/_documentation/workflow/platformsh/README.md
  scripts/provision.yml
  scripts/roles/cikit-composer/tasks/main.yml
  scripts/roles/cikit-mssql/tasks/main.yml
  scripts/roles/cikit-platformsh-cli/tasks/main.yml
  scripts/roles/cikit-platformsh-cli/vars/main.yml
  scripts/roles/cikit-ruby/tasks/main.yml
Labels: enhancement

#109 #108: Update installation instructions for WSL
  docs/_documentation/install-on-wsl/README.md
  docs/_documentation/install-on-wsl/patches/vagrant-1.9.5-issue-9298.patch
  docs/_documentation/install-on-wsl/patches/vagrant-1.9.6-issue-9298.patch
  docs/_documentation/install-on-wsl/patches/vagrant-1.9.7-issue-9298.patch
  docs/_documentation/install-on-wsl/patches/vagrant-1.9.8-issue-9298.patch
  docs/_documentation/install-on-wsl/patches/vagrant-2.0.0-issue-9298.patch
  docs/_documentation/install-on-wsl/patches/vagrant-2.0.1-issue-9298.patch
  docs/_documentation/install-on-wsl/wsl-provision.sh
Labels: enhancement

#113 Fixes #112: Fix "Directory" Apache2 definition for local environment
  scripts/roles/cikit-apache2/templates/vhosts.conf.j2
Labels: bug

#111 #110: Try to get rid of Vagrant and VirtualBox in favor of VM-ish Docker container
  .gitignore
  env/rm.yml
  env/start.yml
  env/stop.yml
  env/tasks/create.yml
  env/tasks/do.yml
  env/tasks/is-running.yml
  env/tasks/rm.yml
  env/tasks/start.yml
  env/tasks/stop.yml
  lib/__init__.py
  lib/variables.py
Labels: enhancement, in progress
